INSERT INTO plants (id, nickname, species, pot_size, watering_method, watering_instructions, room_id)
VALUES
  (1, 'Basil in silver pot', 'Ocimum basilicum', 'small', 'bottom', 'keep soil consistently moist but not waterlogged', 1),
  (2, 'Basil in orange pot, sitting in bowl', 'Ocimum basilicum', 'small', 'bottom', 'keep soil consistently moist but not waterlogged', 1),
  (3, 'Monstera in green pot', 'Monstera deliciosa', 'medium', 'top', 'Water when the top 2–3 inches of soil are dry', 1),
  (4, 'Fiddle leaf fig in white pot', 'Ficus lyrata', 'medium', 'top', 'Water when the top 2–3 inches of soil are dry', 1),
  (5, 'Poinsettia (the Christmas plant) in white tin with blue art', 'Euphorbia pulcherrima', 'small', 'top', 'Water when the top inch of soil feels dry', 1),
  (6, 'Polka dot begonia in plastic orange pot', 'Begonia maculata', 'small', 'bottom', 'keep soil consistently moist but not waterlogged', 1),
  (7, 'Oxalis triangularis (the butterfly plant) in orange clay pot', 'Oxalis triangularis', 'small', 'bottom', 'Water when the top inch of soil is dry; reduce significantly during dormancy', 1),
  (8, 'Oxalis triangularis (the butterfly plant) in red pot', 'Oxalis triangularis', 'small', 'bottom', 'Water when the top inch of soil is dry; reduce significantly during dormancy', 1),
  (9, 'Orchid in white pot', 'Phalaenopsis', 'small', 'bottom', 'Soak when potting medium is dry and roots turn silvery-gray; avoid water in crown', 1),
  (10, 'Boston fern in funky white pinecone pot', 'Nephrolepis exaltata', 'medium', 'bottom', 'keep soil consistently moist but not waterlogged', 1),
  (11, 'Pothos (Devil''s Ivy) in the white pot on the wooden bookshelf', 'Epipremnum aureum', 'small', 'top', 'Water when the top 1–2 inches of soil are dry', 1),
  (12, 'Spider plant in little orange plastic pot on the bookshelf', 'Chlorophytum comosum', 'small', 'bottom', 'Water when the top 1–2 inches of soil are dry', 1),
  (13, 'Basil in orange plastic pot sitting on the books', 'Ocimum basilicum', 'small', 'bottom', 'keep soil consistently moist but not waterlogged', 2),
  (14, 'Basil in orange plastic pot sitting on the books, sitting in bowl', 'Ocimum basilicum', 'small', 'bottom', 'keep soil consistently moist but not waterlogged', 2),
  (15, 'Pothos (Devil''s Ivy) in the white pot by the books', 'Epipremnum aureum', 'small', 'top', 'Water when the top 1–2 inches of soil are dry', 2),
  (16, 'Basil in grey plastic pot sitting on the grey plate', 'Ocimum basilicum', 'small', 'bottom', 'keep soil consistently moist but not waterlogged', 2),
  (17, 'Pothos (Devil''s Ivy) in the white and blue pot on the shelf', 'Epipremnum aureum', 'small', 'top', 'Water when the top 1–2 inches of soil are dry', 3),
  (18, 'Black Pagoda lipstick plant (the hanging plant)', 'Aeschynanthus marmoratus', 'small', 'bottom', 'Water with room-temperature water when top 1–2 inches of soil are dry', 3),
  (19, 'Basil in orange clay pot', 'Ocimum basilicum', 'small', 'bottom', 'keep soil consistently moist but not waterlogged', 4),
  (20, 'Basil in grey plastic pot', 'Ocimum basilicum', 'small', 'bottom', 'keep soil consistently moist but not waterlogged', 4),
  (21, 'Wisteria in the giant blue pot', 'Wisteria sinensis', 'large', 'top', 'Water deeply when the top 1–2 inches are dry; keep consistently moist during hot summer days', 4),
  (22, 'Bowles'' Mauve in the short but wide orange clay pot', 'Erysimum linifolium', 'medium', 'top', 'Water when the top 1–2 inches of soil are dry (ensure sharp drainage)', 4),
  (23, 'Thyme in the metal funky pot thing', 'Thymus vulgaris', 'small', 'top', 'Water when the top 1–2 inches of soil are dry (ensure sharp drainage and avoid soggy roots)', 4),
  (24, 'Marjoram in the small orange clay pot', 'Origanum majorana', 'small', 'top', 'Water when the top 1 inch of soil is dry (ensure sharp drainage)', 4),
  (25, 'Geranium in the red plastic pot', 'Pelargonium hortorum', 'medium', 'top', 'Water when the top 1–2 inches of soil are dry (water soil directly, avoid wetting foliage)', 4),
  (26, 'Canna Lily in the medium-large grey pot', 'Canna indica', 'medium', 'top', 'Water deeply when the top 1–2 inches are dry; keep consistently moist during hot summer days', 4),
  (27, 'Blue Potato Bush in the plastic orange pot', 'Lycianthes rantonnetii', 'small', 'top', 'Water when the top 1–2 inches of soil are dry (ensure sharp drainage)', 4),
  (28, 'Camelia in the large orange clay pot that is shaped like a flower', 'Camellia japonica', 'large', 'top', 'Keep soil evenly moist; water deeply when the top 1 inch feels dry', 4),
  (29, 'Lavender in the small orange clay pot', 'Lavandula angustifolia', 'small', 'top', 'Allow top 2 inches (or most of the pot) to dry out between deep waterings', 4),
  (30, 'Halcyon hosta in plastic grey pot', 'Hosta Halcyon', 'medium', 'top', 'Keep soil consistently moist but well-drained; water at the base to protect blue leaf wax', 4),
  (31, 'Halcyon hosta in plastic orange pot', 'Hosta Halcyon', 'medium', 'top', 'Keep soil consistently moist but well-drained; water at the base to protect blue leaf wax', 4),
  (32, 'Halcyon hosta in plastic orange pot', 'Hosta Halcyon', 'medium', 'top', 'Keep soil consistently moist but well-drained; water at the base to protect blue leaf wax', 4),
  (33, 'Fern in the plastic grey pot', 'Dryopteris filix-mas', 'medium', 'top', 'Keep soil consistently moist and humus-rich; water at the base around the edge to avoid the crown', 4),
  (34, 'Fern in the plastic grey pot', 'Dryopteris filix-mas', 'medium', 'top', 'Keep soil consistently moist and humus-rich; water at the base around the edge to avoid the crown', 4),
  (35, 'Ivy in the small orange plastic pot', 'Hedera helix', 'small', 'top', 'Water thoroughly when the top inch of soil is dry; ensure sharp drainage and avoid soggy roots', 4),
  (36, 'Geranium in the small grey plastic pot', 'Pelargonium hortorum', 'small', 'top', 'Water when the top 1–2 inches of soil are dry (water soil directly, avoid wetting foliage)', 4);